# Generated by Django 3.2.7 on 2022-04-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(db_column='dept_id', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='dname', max_length=50, unique=True)),
                ('location', models.CharField(db_column='loc', max_length=50)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(db_column='emp_id', max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ename', max_length=255, unique=True)),
                ('designation', models.CharField(db_column='desig', max_length=40)),
                ('joining_date', models.DateField(db_column='doj')),
                ('basic', models.DecimalField(db_column='basic', decimal_places=2, max_digits=12)),
                ('allowence', models.DecimalField(db_column='allowence', decimal_places=2, max_digits=12)),
                ('address', models.CharField(db_column='add_line', max_length=500)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('contact_no', models.CharField(db_column='contact_no', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_emp_reg.department')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
