from django.shortcuts import render
from app_emp_reg.models import Department,Employee
from django.views.generic import DetailView,ListView,UpdateView
from django.urls import reverse,reverse_lazy
from app_emp_reg.forms import EmloyeeForm

# Create your views here.
def index_main(request):
    return render(request, 'app_emp_reg/main.html')

def index_employee(request):
    list_emp = Employee.objects.order_by('name')
    dict_emp = {'emp_records': list_emp}
    return render(request, 'app_emp_reg/employee_list.html', context=dict_emp)

def index_raw_emp(request):
    list_emp = Employee.objects.order_by('name')
    dict_emp = {'emp_records': list_emp}
    return render(request, 'app_emp_reg/raw_emp.html', context=dict_emp)

def index_department(request):
    list_dept = Department.objects.order_by('name')
    dict_dept = {'dept_records': list_dept}
    return render(request, 'app_emp_reg/department.html', context=dict_dept)\

class EmployeeListView(ListView):
    model = Employee
    template_name = 'app_emp_reg/employee_list.html'
    # employee_list is the variable generated by ListVIew model

class EmployeeUpdateView(UpdateView):
    form_class = EmloyeeForm
    model = Employee
    #fields = '__all__'
    template_name = 'app_emp_reg/employee_form.html'
    success_url = reverse_lazy('app_emp_reg:index_employees')